export const photoServer = [
    {
        name: 'cap2013', 
        url : ["../img/cap2013/WP_20160325_004.jpg", "../img/cap2013/WP_20160325_005.jpg", "../img/cap2013/WP_20160325_007.jpg", "../img/cap2013/WP_20160325_008.jpg"],
        description: 'street cap2013 photo',
        comments: [ 
                    {   userName: 'Pavel',
                        idComment: 1,
                        userComment: 'Hello',
                        date: '25.12.2015',
                        time: '10:28',
                        like: 15,
                        dislike: 33,
                        answer: [ 
                            {   userNameAnswer: 'Viktor',
                                idAnswer: 1,
                                userCommentAnswer: 'Hello Pavel', 
                                date: '25.12.2015',
                                time: '10:28',
                                likeAnswer: 75,
                                dislikeAnswer: 3,
                            },
                            {   userNameAnswer: 'Alex',
                                idAnswer: 2,
                                userCommentAnswer: 'Hi Pavel',
                                date: '01.12.2013',
                                time: '22:22',
                                likeAnswer: 67,
                                dislikeAnswer: 63,
                            },
                            {   userNameAnswer: 'Alexey',
                                idAnswer: 3,
                                userCommentAnswer: 'Hi Pavel',
                                date: '01.12.2007',
                                time: '22:22',
                                likeAnswer: 50,
                                dislikeAnswer: 2,
                            },
                        ],
                    }, 
                    {   userName: 'Sasha',
                        idComment: 2,
                        userComment: 'Looook',
                        date: '25.12.2015',
                        time: '10:28',
                        like: 190,
                        dislike: 3,
                        answer: [ 
                            {   userNameAnswer: 'Mary',
                                idAnswer: 4,
                                userCommentAnswer: 'Hello Sasha',
                                date: '25.12.2015',
                                time: '10:28',
                                likeAnswer: 5,
                                dislikeAnswer: 3,
                            },
                            {   userNameAnswer: 'Kosty',
                                idAnswer: 5,
                                userCommentAnswer: 'Hi Sasha',
                                date: '01.12.2013',
                                time: '22:22',
                                likeAnswer: 5,
                                dislikeAnswer: 3,
                            },
                        ],
                    }, 
                    {   userName: 'Evgenya',
                        idComment: 3,
                        userComment: 'Hello Guys.',
                        date: '03.08.2007',
                        time: '10:28',
                        like: 5,
                        dislike: 3,
                        answer: [
                            {   userNameAnswer: 'Mary',
                                idAnswer: 6,
                                userCommentAnswer: 'Hello Sasha',
                                date: '25.12.2015',
                                time: '10:28',
                                likeAnswer: 5,
                                dislikeAnswer: 3,
                            },
                        ],
                    },
                ],
                    
    },
    {
        name: 'cap2015',
        url : ["../img/cap2015/WP_20160831_18_56_31_Pro.jpg", "../img/cap2015/WP_20160831_18_56_38_Pro.jpg", "../img/cap2015/WP_20160831_18_57_06_Pro.jpg", "../img/cap2015/WP_20160831_18_57_12_Pro.jpg"],
        description: 'street cap2015 photo',
        comments: [ {   userName: 'Vladislav',
                        idComment: 1,
                        userComment: 'Hello pavel',
                        date: '01.10.2017',
                        time: '10:28',
                        like: 5,
                        dislike: 3,
                        answer: [],
                    } ],
    },
    {
        name: 'IMG-6437',
        url : ["../img/IMG_6437.jpeg", "../img/IMG_6784.jpeg", ], //"../img/.jpg", "../img/.jpg", "../img/.png"
        description: 'park IMG-6437 photo',
        comments: [ {   userName: 'Igor',
                        idComment: 1,
                        userComment: 'Hello World!',
                        date: '25.12.2010',
                        time: '10:28',
                        like: 5,
                        dislike: 3,
                        answer: [],
                    } ],
    },
    {
        name: 'IMG_6784',
        url : [ "../img/IMG_6784.jpeg", "../img/IMG_6437.jpeg", "../img/garland.png", "../img/dark-theme.jpg"],
        description: 'park IMG_6784 photo',
        comments: [ {   userName: 'Evgenya',
                        idComment: 1,
                        userComment: 'Hello Guys.',
                        date: '03.08.2007',
                        time: '10:28',
                        like: 5,
                        dislike: 3,
                        answer: [],
                    } ],
    },
    {
        name: 'scale_1200',
        url : [ "../img/scale_1200.jpg", "../img/bodyFon.jpeg", "../img/dark-theme.jpg", "../img/shark.png"],
        description: 'dirt ale_1200 photo',
        comments: [ {   userName: 'Maria',
                        idComment: 1,
                        userComment: 'HI!!!!!!!',
                        date: '06.05.2020',
                        time: '10:28',
                        like: 5,
                        dislike: 3,
                        answer: [],
                    } ],
    },
]; 

